### ISSUE TITLE
'>' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by ginsm** [dennisvang/tufup-example#18]
I'm having an issue when `client.py` tries to compare `target_meta.version` and `self.current_archive.version` ([here](https://github.com/dennisvang/tufup/blob/08ff73e904560b23a5076523a74ef1c751200a7f/src/tufup/client.py#L167)). I'm pretty lost as I am setting the version as far as I'm aware? I largely used this repo and [these examples](https://github.com/dennisvang/tufup/tree/master/examples) to try and figure everything out.
 
 Here are the files pertaining to the repository side:
 [Repo Settings](https://github.com/ginsm/nazarick-launcher/blob/main/repo_settings.py)
 [Repo Init](https://github.com/ginsm/nazarick-launcher/blob/main/repo_init.py)
 [Repo Add bundle](https://github.com/ginsm/nazarick-launcher/blob/main/repo_add_bundle.py)
 
 And here are the files pertaining to the client side:
 [Client Settings](https://github.com/ginsm/nazarick-launcher/blob/main/src/modules/tufupsettings.py)
 [Client Init](https://github.com/ginsm/nazarick-launcher/blob/f5516b25db55cb9f570469c51922db19440b8ef5/src/app.py#L53)
 
 And here are the steps I'm taking:
 1. Initialize the repo.
 2. [Build the app](https://github.com/ginsm/nazarick-launcher/blob/f5516b25db55cb9f570469c51922db19440b8ef5/pyinstaller/build-prod.bat) (ensuring only one bundle is in the dist dir).
 3. Add the bundle to the repo.
 4. Start the server.
 5. Start the app.
 
Here's some logs that might help:
<details>
  <summary>Full Error</summary>
  
```
Trusted root metadata copied to cache.
Traceback (most recent call last):
  File "F:\Projects\Active\nazarick-launcher\src\app.py", line 83, in <module>
    main()
  File "F:\Projects\Active\nazarick-launcher\src\app.py", line 19, in main
    tufupClient()
  File "F:\Projects\Active\nazarick-launcher\src\app.py", line 78, in tufupClient
    if client.check_for_updates():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%UserProfile%\AppData\Roaming\Python\Python312\site-packages\tufup\client.py", line 163, in check_for_updates
    all_new_targets = dict(
                      ^^^^^
  File "%UserProfile%\AppData\Roaming\Python\Python312\site-packages\tufup\client.py", line 167, in <genexpr>
    and target_meta.version > self.current_archive.version
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

</details>

<details>
  <summary>HTTP Server Log</summary>
  
```
F:\Projects\Active\nazarick-launcher>python -m http.server -d pyinstaller/temp/repository
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::1 - - [22/Oct/2023 06:51:53] code 404, message File not found
::1 - - [22/Oct/2023 06:51:53] "GET /metadata/2.root.json HTTP/1.1" 404 -
::1 - - [22/Oct/2023 06:51:53] "GET /metadata/timestamp.json HTTP/1.1" 200 -
::1 - - [22/Oct/2023 06:51:53] "GET /metadata/snapshot.json HTTP/1.1" 200 -
::1 - - [22/Oct/2023 06:51:54] "GET /metadata/targets.json HTTP/1.1" 200 -
```

</details>

It appears to be trying to find `2.root.json` which doesn't exist? This occurs when I run either the bundled app or dev app. Any help would be greatly appreciated, thanks! :)

**Comment by dennisvang** [comment]
@ginsm Thanks for taking an interest in tufup. 
Could you please edit your question to include the full error and server log as text, instead of linking to pastebin?

**Comment by dennisvang** [comment]
>...  it appears to be trying to find `2.root.json` which doesn't exist?

`python-tuf` always tries to download a new version of `root.json`. That's normal. See [TUF client workflow][1].

[1]: https://theupdateframework.github.io/specification/latest/#load-trusted-root

**Comment by dennisvang** [comment]
@ginsm Could you also post the content of the `"targets"` section from your `targets.json`?

**Comment by dennisvang** [comment]
@ginsm Something is probably going wrong when parsing the version from your target file path.

Could run your app with logging level set to `logging.DEBUG`, and then post the command line output? 

(please make sure to remove any sensitive information from the log before posting)

**Comment by ginsm** [comment]
> @ginsm Thanks for taking an interest in tufup. Could you please edit your question to include the full error and server log as text, instead of linking to pastebin?
> > ...  it appears to be trying to find `2.root.json` which doesn't exist?
> 
> `python-tuf` always tries to download a new version of `root.json`. That's normal. See [TUF client workflow](https://theupdateframework.github.io/specification/latest/#load-trusted-root).

Done and thanks for the info!

> @ginsm This is probably caused by the whitespace in your `APP_NAME`.
> 
> [Here](https://github.com/dennisvang/tufup/blob/08ff73e904560b23a5076523a74ef1c751200a7f/src/tufup/common.py#L18)'s how tufup parses the version from the filename:
> 
> ```python
> r'^(?P<name>[\w-]+)-(?P<version>.+)(?P<suffix>\.tar\.gz|\.patch)$'
> ```

Yup, that seems to have resolved the issue. Thanks for the quick response! :grin:
