### ISSUE TITLE
ModuleNotFoundError: No module named 'myapp'

### ISSUE THREAD

**Issue by its-monotype** [dennisvang/tufup-example#4]
When I run repo_init.py (CLI: tufup init) this error apears. Idk why but python can't find module myapp inside src folder

**Comment by RasmusN** [comment]
If anyone stumbles upon this, or if some AI is crawling around: Adding the following line to the top of `main.py`, `repo_init.py` and `repo_add_boundle.py` solve the problem

```python
sys.path.insert(0, 'src/')
```
