### ISSUE TITLE
Why updates is not applied 

### ISSUE THREAD

**Issue by 0x0645** [dennisvang/tufup-example#7]
I built the example with another version and the update got downloaded in the temp file but the files in the app dir not updated and stayed on the old version and still asking for update

**Comment by 0x0645** [comment]
I read there that there is 

> A default install script is then started, which copies the new files and folders from the temporary directory to the current app installation directory. On Windows, this script is started in a new process, after which the currently running process will exit.

**Comment by dennisvang** [comment]
@0x0645 Could you provide some more background? For example:

- What platform are you using?
- What version of python?
- Are you using a clone of the repository, or did you customize it in some way?
- How exactly are you running the app?
- Did you check to see if the install dir contains a log file? If so, what does it contain?

**Comment by 0x0645** [comment]
What platform are you using?
Windows

> What version of python?

3.9

> Are you using a clone of the repository, or did you customize it in some way?

clone just trying the library 

> How exactly are you running the app?

followed the instruction the readme


> Did you check to see if the install dir contains a log file? If so, what does it contain?

no there is no log file

**Comment by dennisvang** [comment]
And just to be sure: did you confirm installation by entering `y` in the command window?

**Comment by 0x0645** [comment]
yes also I can see the new version in my temp file

**Comment by 0x0645** [comment]
just check after opening it again it shows
DEBUG:tufup.client:files extracted to C:\Users\Mostafa\AppData\Local\Temp\tufup                                         
Install update in C:\Users\Mostafa\AppData\Local\Programs\my_app? [y]/n 

I typed y and it close instantly

**Comment by dennisvang** [comment]
> I typed y and it close instantly

This looks normal: After downloading the new version to the temp dir, once you type `y`, all it needs to do is move the file(s) to the install dir. This can happen quite fast. The app then closes and does *not* restart by itself, so you'll need to restart it manually.

And is this windows 10 or 11?

**Comment by 0x0645** [comment]
windows 10 

when starting it again it still showing 
![image](https://user-images.githubusercontent.com/30774866/195059693-5e217a0d-f07e-4c7e-a626-3a1b52af2fa7.png)
but the version in` C:\Users\Mostafa\AppData\Local\Programs\my_app`
close instantly which means there is no update

**Comment by dennisvang** [comment]
It looks like you are running the `main.exe` from your temp folder, is that correct?

**Comment by 0x0645** [comment]
I think i am starting to understand but what is` C:\Users\Mostafa\AppData\Local\Programs\my_app` why update got installed there it should be installed in `INSTALL_DIR` which is in my system is` C:\Users\Mostafa\Desktop\disktop\tufup-example\temp\my_app` or I am missing something

**Comment by 0x0645** [comment]
> It looks like you are running the main.exe from your temp folder, is that correct?

No I am running it from my INSTALL_DIR

**Comment by dennisvang** [comment]
It looks like there's some confusion here, caused by the way you are running the example app:

In your case, `C:\Users\Mostafa\AppData\Local\Programs\my_app` is the proper `INSTALL_DIR` for the default example, so you should always run the `main.exe` file from there.

The install dir that you mention, `C:\Users\Mostafa\Desktop\disktop\tufup-example\temp\my_app`, is actually the development install dir. This should only be used for development of the `tufup-example` package itself.

Have a look at the [settings file][1] to see how this works.

[1]: https://github.com/dennisvang/tufup-example/blob/2af43175d39417f9d3d855d7e8fb2cb6ebd3c155/src/myapp/settings.py#L38

**Comment by 0x0645** [comment]
I understand now I am new to pyinstaller so the frozen thing was new to me and I didn't read the.
Thank you for your help.

**Comment by dennisvang** [comment]
@0x0645 Happy to help. I understand this can be a bit confusing, so I'll try to make the readme a bit clearer.
